version: '3'
services:
  db:
    image: mysql:8.0
    expose:
      - '3306'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: redis:latest
    expose:
      - '6379'
    ports:
      - '6379:6379'
volumes:
  db-data:
